version: "3.5"

services: 
  react-router:
    build: 
      context: react-router
    ports:
    - "3000:80"
  nextjs:
    build: 
      context: nextjs
  nginx:
    build: 
      context: nextjs
      dockerfile: Dockerfile.nginx
    ports:
    - "3001:80"
  
  
